### ISSUE TITLE
Add CSS Framework

### ISSUE THREAD

**Issue by hoehlars** [Timotheeee/PSIT3-HS19-IT18a_ZH-TeamIP2#15]

**Comment by erwintran0** [comment]
Instead of adding the normal bootstrap to the project, I found this version, which seems to work perfectly with vue. 
All functionalities from bootstrap are useable, but with Bootstrap-Vue additional tags are provided (which seem to do the same). -> https://bootstrap-vue.js.org/docs/components/alert
